
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\ukncbtl
shallow_clone: true

branches:
  only:
    - master

matrix:
  fast_finish: false

configuration:
  - Debug
  - Release
  - Product

environment:
  matrix:
    - toolchain: msvc13
      platform: Win32

build:
  project: emulator\UKNCBTL-VS2013.sln

